### PR TITLE
This Week in RustFest - Talks and more

### PR DESCRIPTION
**Pull request by badboy**
image

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀

As a side note, I took a look at the speakers page and it seems to be something off. Is it possible that the title is missing for Brian?

image

**Comment by badboy** [comment]
Nope, Brian is co-speaking with Aimee (the fact that the pictures are not aligned are ... due to poor CSS skills)

**Comment by apiraino** [comment]
The CSS blocks to ~1200 px width anyways so I shrinked a bit the title image. Hope it's ok :angel:

**Comment by badboy** [comment]
> The CSS blocks to ~1200 px width anyways so I shrinked a bit the title image. Hope it's ok 👼

next time just let me know, converting that into an jpg seems suboptimal

**Comment by apiraino** [comment]
> next time just let me know, converting that into an jpg seems suboptimal

pls, allow me to fix it.

Would a png 1200 px do better?

**Comment by badboy** [comment]
> > next time just let me know, converting that into an jpg seems suboptimal
> 
> pls, allow me to fix it.
> 
> Would a png 1200 px do better?

It's easier to create that from the source material than to shrink bigger images ;)

**Comment by apiraino** [comment]
> It's easier to create that from the source material than to shrink bigger images ;)

ok, then I'll simply revert. sorry about that :^)

**Comment by robertohuertasm** [comment]
@badboy you've got a PR fixing the speakers page in the main repo.

**Comment by RafaelaWetzel** [comment]
Aimee requested to have her bio shortened to

"Aimee Zhu
Editor of Rustinblockchain.org; Building dev community for Rust Blockchain and Nervos Network; Organized RustCon Asia 2019."

**Comment by badboy** [comment]
@RafaelaWetzel done!

**Pull request merged**
