### PR TITLE
Add readme with build instructions

### PR DESCRIPTION
**Pull request by dns2utf8**
Wrote down the easy way for building the blog or any of the gh-pages websites.

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]
This looks fine. Fairly easily to build locally on most machines though with just `rm Gemfile.lock && bundle install && jekyll serve`

**Comment by skade** [comment]
Why is `rm Gemfile.lock` necessary?

**Comment by gandro** [comment]
With regards to the lockfile: On my Linux machine, I need to update the json gem from 1.8.3 to 1.8.5 in order for the build to succeed.

**Comment by skade** [comment]
Then do the update, commit the fixed Gemfile.lock (1.8.3 not being compatible with newer Rubies is the issue, AFAIK). Don't have everyone repeat it. :)

**Comment by dns2utf8** [comment]
Well the last time I had ruby installed on my main system it trashed it after one or two updated so I like keeping it inside a container.
So I pushed the updated `Gemfile.lock` and added a text for native installs

**Pull request merged**
