### PR TITLE
Prepare next TWIRF2

### PR DESCRIPTION
**Pull request by dns2utf8**
- [ ] Announce first sponsor?
- [x] Talk about hotels
- [x] Maybe repeate how much we use public transportation
- [x] Maybe announce the first batch of tickets

### CODE REVIEW

**Comment by Hoverbear** [comment]
@flaki Did you get access to Tito yet? We need to figure out when these batches are being released.

I propose:

- Monday at 20:00 CEST
- Wednesday at 14:00 CEST
- Friday at 9:00 CEST

**Comment by dns2utf8** [comment]
I would like to stretch it over at lease two weeks. Maybe start Wednesday?

**Comment by flaki** [comment]
I don't think I got it yet, afaik @skade needs to set up stuff first...

**Comment by Hoverbear** [comment]
@RustFestEU/zurich-2017 review please =D We would like to publish today!

**Comment by gandro** [comment]
The title still mentions tickets, I guess we should change that. Other than that, looks good to me!

**Comment by aochagavia** [comment]
LGTM

**Comment by dns2utf8** [comment]
I updated the title. Go?

**Comment by skade** [comment]
> I don't think I got it yet, afaik @skade needs to set up stuff first...

You should have gotten an invite to your mozilla address. But we still need to clarify tax things between EU and Switzerland.

**Pull request merged**
