### PR TITLE
Add blogpost announcing Parity workshops

### PR DESCRIPTION
**Pull request by gandro**
Short and simple.

image

### CODE REVIEW

**Comment by apiraino** [comment]
@gandro thank you for that :+1:  However let's don't merge this one immediately. Parity contacted us for some changes concerning the workshops.

Tomorrow I will update this PR accordingly.

**Comment by gandro** [comment]
Fine with me! Thank you for the heads-up.

**Comment by apiraino** [comment]
- new logo
- changed names of workshop hosts

screenshot_2018-11-15 more workshops

**Comment by badboy** [comment]
Let's post that tomorrow (we got tshirts today)

**Comment by apiraino** [comment]
> Let's post that tomorrow (we got tshirts today)

done!

**Pull request merged**
