### PR TITLE
(draft) TWiRF2: RustBridge

### PR DESCRIPTION
**Pull request by gandro**
TODO:

- [x] links to bio/speakers
- [x] signup link
- [x] social media image

image

### CODE REVIEW

**Comment by ghost** [comment]
So, it's very likely that I won't have a co-organizer/teacher. Maybe spontaneously, but in the announcements and everything, it's just me. As for the bio:

```
Olivia is a sinology student from Berlin, as well as a hobbyist programmer and open source contributor. She's the RustBridge project lead, as well as a member of the Rust Community Team.
```

Is that enough information?

**Comment by gandro** [comment]
That's perfect! Thank you! I'll add it to the main page.

In the past we had a sign-up link to a a simple google form for RustBridge. Do you have something similar?

**Comment by ghost** [comment]
@gandro Yes, of course: https://airtable.com/shr90tp1ax1yJk8aN

**Comment by ghost** [comment]
For the thumbnail, we could go for a simple image edit, like this:

rb

**Comment by gandro** [comment]
Awesome thumbnail @oe - thanks for doing this! The post is now ready to publish, will do it Tuesday around noon.

**Pull request merged**
